using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    class EvenFibonacci
    {
        static void Main(string[] args)
        {
            int sum = 0;
            foreach (var number in fibonacci(4000000))
            {
                if (number%2 == 0)
                {
                    Console.WriteLine(number);
                    sum += number;
                }
            }
            Console.WriteLine("Sum: {0}", sum);
        }

        static IEnumerable<int> fibonacci(int max)
        {
            int a = 0;
            int b = 1;
            int c;
            while(true)
            {
                c = b;
                b += a;
                a = c;
                if (b >= max)
                {
                    break;
                }
                //Console.WriteLine(b);
                yield return b;
            }
        }
    }
}
